version: '2'
services:
  sauce-demo:
    image: steilerdev/sauce-demo:latest
    container_name: sauce-demo
    restart: on-failure:5
    env_file:
      - ./config.env
    environment:
      VIRTUAL_PORT: 3000
      BRANCH: "default"
networks:
  default:
    external:
      name: steilerGroup