version: '2'
services:
  sauce-demo:
    image: steilerdev/sauce:latest
    container_name: sauce-demo
    on-failure: 5
    environment:
        VIRTUAL_HOST: "saucedemo.doe.net"
        VIRTUAL_PORT: 3000
        LETSENCRYPT_HOST: "saucedemo.doe.net"
        LETSENCRYPT_EMAIL: "hostmaster@doe.net"
        BRANCH: "default"
networks:
  default:
    external:
      name: steilerGroup