name: Build & Publish

on: push

env:
  # This will pull the github repo name
  DOCKER_USERNAME: steilerdev
  PKG_NAME: sauce-demo
  NODE_VERSION: 12
  SOURCE_DIR: source
  DIFF_DIR: diff
  BUILD_VANILLA: rootfs/opt/vanilla
  BUILD_MOD: rootfs/opt/mod

# Required secrets:
# DOCKER_PWD            DockerHub password

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout saucelabs/sample-app-web
      uses: actions/checkout@v3
      with:
        repository: saucelabs/sample-app-web
        path: ${{ env.SOURCE_DIR }}
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install npm dependencies & build orig version
      run: |
        npm install --prefix $SOURCE_DIR/
        npm run build --prefix $SOURCE_DIR/
        mv $SOURCE_DIR/build $BUILD_VANILLA
      env:
        CI: false
    - name: Create diff & build diff version
      run: |
        cp -r $DIFF_DIR/* $SOURCE_DIR/
        npm run build --prefix $SOURCE_DIR/
        mv $SOURCE_DIR/build $BUILD_MOD
      env:
        CI: false
    - name: Diffing builds
      run: |
        ! diff -qr $BUILD_MOD $BUILD_VANILLA 
    - name: Package docker artifacts
      run: |
        if [ -d ./rootfs ]; then
          tar -C ./rootfs -czf ./rootfs.tar.gz ./
        else
          for d in */ ; do
            if [ -d ${d%/}/rootfs ]; then
              tar -C ${d%/}/rootfs -czf ${d%/}/rootfs.tar.gz ./
            fi
          done
        fi
    - name: Upload docker artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rootfs
        path: ./**/rootfs.tar.gz

  publish-dockerhub:
    name: Publish Project to DockerHub
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Login to DockerHub
      run: docker login -u $DOCKER_USERNAME -p ${{secrets.DOCKER_PWD}}
    - name: Build the Docker image
      run: |
        if [ -f Dockerfile ]; then
          if [ -f rootfs/rootfs.tar.gz ]; then
            echo "Moving rootfs.tar.gz..."
            mv rootfs/rootfs.tar.gz ./
          fi
          docker build . --file Dockerfile --tag $DOCKER_USERNAME/$PKG_NAME:latest
        else
          for d in */ ; do
            if [ -f ${d%/}/Dockerfile ]; then
              if [ -f rootfs/${d%/}/rootfs.tar.gz ]; then
                mv rootfs/${d%/}/rootfs.tar.gz ${d}
              fi
              docker build ${d} --file ${d%/}/Dockerfile --tag $DOCKER_USERNAME/$PKG_NAME:${d%/}
            fi
          done
        fi
        docker image ls
    - name: Push to DockerHub
      run: docker image push --all-tags $DOCKER_USERNAME/$PKG_NAME
    - name: Update DockerHub readme
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}
        repository: ${{env.DOCKER_USERNAME}}/${{env.PKG_NAME}}
        readme-filepath: ./README.md
        short-description: ${{ github.event.repository.description }}