# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run SauceLabs Tests

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
  workflow_dispatch:

env:
  NODE_VERSION: 12
  APP_URL: 'saucedemo.steilergroup.net'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: saucelabs/sample-app-web
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Setup test for environment
      run: |
        sed -i 's/http:\/\/localhost:3000/https:\/\/${{ env.APP_URL }}/' test/e2e/configs/wdio.shared.conf.js
        sed -i 's/sauceConnect: true/sauceConnect: false/' test/e2e/configs/wdio.saucelabs.conf.js
    - name: Install dependencies
      run: npm install
   # - name: Start service locally
   #   run: npm run start &
    - name: Run Tests
      run: npm run test.e2e.sauce.eu
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

